### ISSUE TITLE
Simpler Query Results

### ISSUE THREAD

**Issue by strawgate** [wrale/mcp-server-tree-sitter#21]
Right now the `run_query` command produces extremely verbose results for captures.

For example, a query which returns the class names in a file result:

```
capture: class.name
end:
  column: 17
  row: 17
file: examples/in_memory_proxy_example.py
start:
  column: 6
  row: 17
text: EchoService
```

If I have 100 classes in the file this is an awfully large amount of data to return!
