### ISSUE TITLE
configure() is ignoring the YAML

### ISSUE THREAD

**Issue by ctrlbrk42** [wrale/mcp-server-tree-sitter#7]
Hi, thanks for your MCP!

I have this in my CLAUDE.md (using Claude Code):

# Startup Initialization Requirements
  1. Run `mcp__tree-sitter__register_project_tool(path="/var/www/atlas", name="Atlas")`
  2. Run `mcp__tree-sitter__configure(config_path="/var/www/atlas/.treesitter.yaml")`

Results in:

● tree-sitter:register_project_tool (MCP)(path: "/var/www/atlas", name: "Atlas")…
  ⎿  {"name": "Atlas", "root_path": "/var/www/atlas", "description": null, "languages": {"bash": 39, "json": 547,
     "markdown": 707, "php": 932, "html": 85, "css": 17, "javascript": 2244, "sql": 2, "typescript": 690, "c": 2,
     "python": 1211, "yaml": 1}, "last_scan_time": 1742211889}

● tree-sitter:configure (MCP)(config_path: "/var/www/atlas/.treesitter.yaml")…
  ⎿  {"cache": {"enabled": true, "max_size_mb": 100, "ttl_seconds": 300}, "security": {"max_file_size_mb": 5,
     "excluded_dirs": [".git", "node_modules", "__pycache__"]}, "language": {"auto_install": false, "default_max_depth":
     5}, "log_level": "INFO"}

The problem is, the configure() always returns default values instead of the values in the /var/www/atlas/.treesitter.yaml file:

```
# cat .treesitter.yaml
cache:
  enabled: true
  max_size_mb: 256
  ttl_seconds: 3600

security:
  max_file_size_mb: 10
  excluded_dirs:
    - .git
    - node_modules
    - __pycache__
    - .cache
    - .claude
    - .config
    - .idea
    - .llm-context
    - .local
    - .npm
    - .phpstorm_helpers
    - .tmp
    - .venv
    - .vscode
    - .w3m
    - admin/logs
    - cache
    - logs
    - tools/data_management/.error_codes_journal
    - tools/code_management/.patch_journal
    - runtime
    - vendor
    - venv
    - .aider*
    - .bash*
    - .claude-preferences.json
    - .codeiumignore
    - .continuerules
    - .env
    - .lesshst
    - .php_history
    - .python-version
    - .viminfo
    - .wget-hsts
    - .windsurfrules

language:
  auto_install: true
  default_max_depth: 7
```

Any help is appreciated.
